---
- include_tasks: splunk_idxvol_prep.yml
  when: "volume_change == 'idxvol_prep'"

- include_tasks: splunk_idxvol_mount.yml
  when: "volume_change == 'idxvol_mount'"

- include_tasks: splunk_idxvol_unmount.yml
  when: "volume_change == 'idxvol_unmount'"

- include_tasks: splunk_idxvol_remove.yml
  when: "volume_change == 'idxvol_remove'"
