---

- name: Remove LV
  lvol:
    vg: "{{vg_name}}"
    lv: "{{idx_lv_name}}"
    state: absent
    force: true

- name: Remove VG
  lvg:
    vg: "{{vg_name}}"
    state: absent
    force: true

- name: Remove partition
  parted:
    device: "{{block_device}}"
    number: 1
    state: absent

# - name: Remove device mapping
#   shell: "dmsetup remove /dev/{{vg_name}}-{{idx_lv_name}}"
