---

- name: Create mount point, add to fstab, and mount
  mount:
    path: "{{idx_mount_point}}"
    src: "/dev/mapper/{{vg_name}}-{{idx_lv_name}}"
    fstype: xfs
    opts: "{{mount_options}}"
    state: '{{item}}'
  with_items:
    - mounted
    - present
